import type { GatewayModel, ListedModel } from "@artfct-ai/adapters/gateway/types";

/** Anthropic models as the models.dev catalog listed them on 2026-09-25, newest first. */
export const ANTHROPIC_MODELS: ListedModel[] = [
  {
    id: "claude-opus-5-5",
    name: "Claude Opus 5.5",
    released: "2026-09-22",
  },
  {
    id: "claude-fable-5-1",
    name: "Claude Fable 5.1",
    released: "2026-09-01",
  },
  {
    id: "claude-opus-5",
    name: "Claude Opus 5",
    released: "2026-07-24",
  },
  {
    id: "claude-sonnet-5",
    name: "Claude Sonnet 5",
    released: "2026-06-29",
  },
  {
    id: "claude-fable-5",
    name: "Claude Fable 5",
    released: "2026-06-07",
  },
  {
    id: "claude-opus-4-8",
    name: "Claude Opus 4.8",
    released: "2026-05-28",
  },
  {
    id: "claude-opus-4-7",
    name: "Claude Opus 4.7",
    released: "2026-04-14",
  },
  {
    id: "claude-sonnet-4-6",
    name: "Claude Sonnet 4.6",
    released: "2026-02-17",
  },
  {
    id: "claude-opus-4-6",
    name: "Claude Opus 4.6",
    released: "2026-02-04",
  },
  {
    id: "claude-opus-4-5",
    name: "Claude Opus 4.5",
    released: "2025-11-24",
  },
  {
    id: "claude-haiku-4-5",
    name: "Claude Haiku 4.5",
    released: "2025-10-15",
  },
  {
    id: "claude-sonnet-4-5",
    name: "Claude Sonnet 4.5",
    released: "2025-09-29",
  },
];

/** A slice of the OpenRouter tool-calling models and the presets on the key, on 2026-09-25. */
export const OPENROUTER_MODELS: GatewayModel[] = [
  {
    kind: "model",
    id: "openrouter/z-ai/glm-5.3-prime",
    vendor: "z-ai",
    name: "Z.ai: GLM 5.3 Prime",
    released: "2026-09-23",
  },
  {
    kind: "model",
    id: "openrouter/anthropic/claude-opus-5.5",
    vendor: "anthropic",
    name: "Anthropic: Claude Opus 5.5",
    released: "2026-09-22",
  },
  {
    kind: "model",
    id: "openrouter/anthropic/claude-opus-5.5:batch",
    vendor: "anthropic",
    name: "Anthropic: Claude Opus 5.5 (batch)",
    released: "2026-09-22",
  },
  {
    kind: "model",
    id: "openrouter/z-ai/glm-5.3-flashx",
    vendor: "z-ai",
    name: "Z.ai: GLM 5.3 FlashX",
    released: "2026-09-18",
  },
  {
    kind: "model",
    id: "openrouter/deepseek/deepseek-v4.1-flash",
    vendor: "deepseek",
    name: "DeepSeek: DeepSeek V4.1 Flash",
    released: "2026-09-10",
  },
  {
    kind: "model",
    id: "openrouter/deepseek/deepseek-v4.1-flash:batch",
    vendor: "deepseek",
    name: "DeepSeek: DeepSeek V4.1 Flash (batch)",
    released: "2026-09-10",
  },
  {
    kind: "model",
    id: "openrouter/google/gemini-3.8-flash",
    vendor: "google",
    name: "Google: Gemini 3.8 Flash",
    released: "2026-09-02",
  },
  {
    kind: "model",
    id: "openrouter/google/gemini-3.8-flash:batch",
    vendor: "google",
    name: "Google: Gemini 3.8 Flash (batch)",
    released: "2026-09-02",
  },
  {
    kind: "model",
    id: "openrouter/z-ai/glm-5.3-flash",
    vendor: "z-ai",
    name: "Z.ai: GLM 5.3 Flash",
    released: "2026-08-26",
  },
  {
    kind: "model",
    id: "openrouter/z-ai/glm-5.3-flash:batch",
    vendor: "z-ai",
    name: "Z.ai: GLM 5.3 Flash (batch)",
    released: "2026-08-26",
  },
  {
    kind: "model",
    id: "openrouter/deepseek/deepseek-v4-flash-vision-exp",
    vendor: "deepseek",
    name: "DeepSeek: DeepSeek V4 Flash Vision Exp",
    released: "2026-08-21",
  },
  {
    kind: "model",
    id: "openrouter/z-ai/glm-5.3",
    vendor: "z-ai",
    name: "Z.ai: GLM 5.3",
    released: "2026-08-18",
  },
  {
    kind: "model",
    id: "openrouter/z-ai/glm-5.3:batch",
    vendor: "z-ai",
    name: "Z.ai: GLM 5.3 (batch)",
    released: "2026-08-18",
  },
  {
    kind: "model",
    id: "openrouter/google/gemini-3.7-flash",
    vendor: "google",
    name: "Google: Gemini 3.7 Flash",
    released: "2026-08-13",
  },
  {
    kind: "model",
    id: "openrouter/google/gemini-3.7-flash:batch",
    vendor: "google",
    name: "Google: Gemini 3.7 Flash (batch)",
    released: "2026-08-13",
  },
  {
    kind: "model",
    id: "openrouter/deepseek/deepseek-v4-pro-0813",
    vendor: "deepseek",
    name: "DeepSeek: DeepSeek V4 Pro 0813",
    released: "2026-08-12",
  },
  {
    kind: "model",
    id: "openrouter/deepseek/deepseek-v4-flash-0731",
    vendor: "deepseek",
    name: "DeepSeek: DeepSeek V4 Flash 0731",
    released: "2026-07-31",
  },
  {
    kind: "model",
    id: "openrouter/anthropic/claude-opus-5",
    vendor: "anthropic",
    name: "Anthropic: Claude Opus 5",
    released: "2026-07-24",
  },
  {
    kind: "model",
    id: "openrouter/anthropic/claude-opus-5:batch",
    vendor: "anthropic",
    name: "Anthropic: Claude Opus 5 (batch)",
    released: "2026-07-24",
  },
  {
    kind: "model",
    id: "openrouter/google/gemini-3.6-flash",
    vendor: "google",
    name: "Google: Gemini 3.6 Flash",
    released: "2026-07-21",
  },
  {
    kind: "model",
    id: "openrouter/google/gemini-3.6-flash:batch",
    vendor: "google",
    name: "Google: Gemini 3.6 Flash (batch)",
    released: "2026-07-21",
  },
  {
    kind: "model",
    id: "openrouter/google/gemini-3.5-flash-lite",
    vendor: "google",
    name: "Google: Gemini 3.5 Flash Lite",
    released: "2026-07-21",
  },
  {
    kind: "model",
    id: "openrouter/google/gemini-3.5-flash-lite:batch",
    vendor: "google",
    name: "Google: Gemini 3.5 Flash Lite (batch)",
    released: "2026-07-21",
  },
  {
    kind: "model",
    id: "openrouter/moonshotai/kimi-k3",
    vendor: "moonshotai",
    name: "MoonshotAI: Kimi K3",
    released: "2026-07-16",
  },
  {
    kind: "model",
    id: "openrouter/moonshotai/kimi-k3:batch",
    vendor: "moonshotai",
    name: "MoonshotAI: Kimi K3 (batch)",
    released: "2026-07-16",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.6-luna-pro",
    vendor: "openai",
    name: "OpenAI: GPT-5.6 Luna Pro",
    released: "2026-07-09",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.6-luna-pro:batch",
    vendor: "openai",
    name: "OpenAI: GPT-5.6 Luna Pro (batch)",
    released: "2026-07-09",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.6-luna",
    vendor: "openai",
    name: "OpenAI: GPT-5.6 Luna",
    released: "2026-07-09",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.6-luna:batch",
    vendor: "openai",
    name: "OpenAI: GPT-5.6 Luna (batch)",
    released: "2026-07-09",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.6-terra-pro",
    vendor: "openai",
    name: "OpenAI: GPT-5.6 Terra Pro",
    released: "2026-07-09",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.6-terra-pro:batch",
    vendor: "openai",
    name: "OpenAI: GPT-5.6 Terra Pro (batch)",
    released: "2026-07-09",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.6-terra",
    vendor: "openai",
    name: "OpenAI: GPT-5.6 Terra",
    released: "2026-07-09",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.6-terra:batch",
    vendor: "openai",
    name: "OpenAI: GPT-5.6 Terra (batch)",
    released: "2026-07-09",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.6-sol-pro",
    vendor: "openai",
    name: "OpenAI: GPT-5.6 Sol Pro",
    released: "2026-07-09",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.6-sol-pro:batch",
    vendor: "openai",
    name: "OpenAI: GPT-5.6 Sol Pro (batch)",
    released: "2026-07-09",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.6-sol",
    vendor: "openai",
    name: "OpenAI: GPT-5.6 Sol",
    released: "2026-07-09",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.6-sol:batch",
    vendor: "openai",
    name: "OpenAI: GPT-5.6 Sol (batch)",
    released: "2026-07-09",
  },
  {
    kind: "model",
    id: "openrouter/anthropic/claude-sonnet-5",
    vendor: "anthropic",
    name: "Anthropic: Claude Sonnet 5",
    released: "2026-06-30",
  },
  {
    kind: "model",
    id: "openrouter/anthropic/claude-sonnet-5:batch",
    vendor: "anthropic",
    name: "Anthropic: Claude Sonnet 5 (batch)",
    released: "2026-06-30",
  },
  {
    kind: "model",
    id: "openrouter/google/gemini-3-pro-image",
    vendor: "google",
    name: "Google: Nano Banana Pro (Gemini 3 Pro Image)",
    released: "2026-06-18",
  },
  {
    kind: "model",
    id: "openrouter/z-ai/glm-5.2",
    vendor: "z-ai",
    name: "Z.ai: GLM 5.2",
    released: "2026-06-16",
  },
  {
    kind: "model",
    id: "openrouter/moonshotai/kimi-k2.7-code",
    vendor: "moonshotai",
    name: "MoonshotAI: Kimi K2.7 Code",
    released: "2026-06-12",
  },
  {
    kind: "model",
    id: "openrouter/google/gemini-3.5-flash",
    vendor: "google",
    name: "Google: Gemini 3.5 Flash",
    released: "2026-05-19",
  },
  {
    kind: "model",
    id: "openrouter/google/gemini-3.5-flash:batch",
    vendor: "google",
    name: "Google: Gemini 3.5 Flash (batch)",
    released: "2026-05-19",
  },
  {
    kind: "model",
    id: "openrouter/google/gemini-3.1-flash-lite",
    vendor: "google",
    name: "Google: Gemini 3.1 Flash Lite",
    released: "2026-05-07",
  },
  {
    kind: "model",
    id: "openrouter/google/gemini-3.1-flash-lite:batch",
    vendor: "google",
    name: "Google: Gemini 3.1 Flash Lite (batch)",
    released: "2026-05-07",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.5-pro",
    vendor: "openai",
    name: "OpenAI: GPT-5.5 Pro",
    released: "2026-04-24",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.5-pro:batch",
    vendor: "openai",
    name: "OpenAI: GPT-5.5 Pro (batch)",
    released: "2026-04-24",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.5",
    vendor: "openai",
    name: "OpenAI: GPT-5.5",
    released: "2026-04-24",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.5:batch",
    vendor: "openai",
    name: "OpenAI: GPT-5.5 (batch)",
    released: "2026-04-24",
  },
  {
    kind: "model",
    id: "openrouter/deepseek/deepseek-v4-pro",
    vendor: "deepseek",
    name: "DeepSeek: DeepSeek V4 Pro 0423",
    released: "2026-04-24",
  },
  {
    kind: "model",
    id: "openrouter/deepseek/deepseek-v4-flash",
    vendor: "deepseek",
    name: "DeepSeek: DeepSeek V4 Flash 0423",
    released: "2026-04-24",
  },
  {
    kind: "model",
    id: "openrouter/moonshotai/kimi-k2.6",
    vendor: "moonshotai",
    name: "MoonshotAI: Kimi K2.6",
    released: "2026-04-20",
  },
  {
    kind: "model",
    id: "openrouter/z-ai/glm-5.1",
    vendor: "z-ai",
    name: "Z.ai: GLM 5.1",
    released: "2026-04-07",
  },
  {
    kind: "model",
    id: "openrouter/z-ai/glm-5v-turbo",
    vendor: "z-ai",
    name: "Z.ai: GLM 5V Turbo",
    released: "2026-04-01",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.4-nano",
    vendor: "openai",
    name: "OpenAI: GPT-5.4 Nano",
    released: "2026-03-17",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.4-nano:batch",
    vendor: "openai",
    name: "OpenAI: GPT-5.4 Nano (batch)",
    released: "2026-03-17",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.4-mini",
    vendor: "openai",
    name: "OpenAI: GPT-5.4 Mini",
    released: "2026-03-17",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.4-mini:batch",
    vendor: "openai",
    name: "OpenAI: GPT-5.4 Mini (batch)",
    released: "2026-03-17",
  },
  {
    kind: "model",
    id: "openrouter/z-ai/glm-5-turbo",
    vendor: "z-ai",
    name: "Z.ai: GLM 5 Turbo",
    released: "2026-03-15",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.4-pro",
    vendor: "openai",
    name: "OpenAI: GPT-5.4 Pro",
    released: "2026-03-05",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.4-pro:batch",
    vendor: "openai",
    name: "OpenAI: GPT-5.4 Pro (batch)",
    released: "2026-03-05",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.4",
    vendor: "openai",
    name: "OpenAI: GPT-5.4",
    released: "2026-03-05",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.4:batch",
    vendor: "openai",
    name: "OpenAI: GPT-5.4 (batch)",
    released: "2026-03-05",
  },
  {
    kind: "model",
    id: "openrouter/google/gemini-3.1-flash-lite-preview",
    vendor: "google",
    name: "Google: Gemini 3.1 Flash Lite Preview",
    released: "2026-03-03",
  },
  {
    kind: "model",
    id: "openrouter/google/gemini-3.1-pro-preview-customtools",
    vendor: "google",
    name: "Google: Gemini 3.1 Pro Preview Custom Tools",
    released: "2026-02-25",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.3-codex",
    vendor: "openai",
    name: "OpenAI: GPT-5.3-Codex",
    released: "2026-02-24",
  },
  {
    kind: "model",
    id: "openrouter/google/gemini-3.1-pro-preview",
    vendor: "google",
    name: "Google: Gemini 3.1 Pro Preview",
    released: "2026-02-19",
  },
  {
    kind: "model",
    id: "openrouter/google/gemini-3.1-pro-preview:batch",
    vendor: "google",
    name: "Google: Gemini 3.1 Pro Preview (batch)",
    released: "2026-02-19",
  },
  {
    kind: "model",
    id: "openrouter/z-ai/glm-5",
    vendor: "z-ai",
    name: "Z.ai: GLM 5",
    released: "2026-02-11",
  },
  {
    kind: "model",
    id: "openrouter/moonshotai/kimi-k2.5",
    vendor: "moonshotai",
    name: "MoonshotAI: Kimi K2.5",
    released: "2026-01-27",
  },
  {
    kind: "model",
    id: "openrouter/z-ai/glm-4.7-flash",
    vendor: "z-ai",
    name: "Z.ai: GLM 4.7 Flash",
    released: "2026-01-19",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.2-codex",
    vendor: "openai",
    name: "OpenAI: GPT-5.2-Codex",
    released: "2026-01-14",
  },
  {
    kind: "model",
    id: "openrouter/z-ai/glm-4.7",
    vendor: "z-ai",
    name: "Z.ai: GLM 4.7",
    released: "2025-12-22",
  },
  {
    kind: "model",
    id: "openrouter/google/gemini-3-flash-preview",
    vendor: "google",
    name: "Google: Gemini 3 Flash Preview",
    released: "2025-12-17",
  },
  {
    kind: "model",
    id: "openrouter/google/gemini-3-flash-preview:batch",
    vendor: "google",
    name: "Google: Gemini 3 Flash Preview (batch)",
    released: "2025-12-17",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.2-chat",
    vendor: "openai",
    name: "OpenAI: GPT-5.2 Chat",
    released: "2025-12-10",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.2-pro",
    vendor: "openai",
    name: "OpenAI: GPT-5.2 Pro",
    released: "2025-12-10",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.2-pro:batch",
    vendor: "openai",
    name: "OpenAI: GPT-5.2 Pro (batch)",
    released: "2025-12-10",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.2",
    vendor: "openai",
    name: "OpenAI: GPT-5.2",
    released: "2025-12-10",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.2:batch",
    vendor: "openai",
    name: "OpenAI: GPT-5.2 (batch)",
    released: "2025-12-10",
  },
  {
    kind: "model",
    id: "openrouter/z-ai/glm-4.6v",
    vendor: "z-ai",
    name: "Z.ai: GLM 4.6V",
    released: "2025-12-08",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.1-codex-max",
    vendor: "openai",
    name: "OpenAI: GPT-5.1-Codex-Max",
    released: "2025-12-04",
  },
  {
    kind: "model",
    id: "openrouter/deepseek/deepseek-v3.2",
    vendor: "deepseek",
    name: "DeepSeek: DeepSeek V3.2",
    released: "2025-12-01",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.1",
    vendor: "openai",
    name: "OpenAI: GPT-5.1",
    released: "2025-11-13",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.1:batch",
    vendor: "openai",
    name: "OpenAI: GPT-5.1 (batch)",
    released: "2025-11-13",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.1-codex",
    vendor: "openai",
    name: "OpenAI: GPT-5.1-Codex",
    released: "2025-11-13",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5.1-codex-mini",
    vendor: "openai",
    name: "OpenAI: GPT-5.1-Codex-Mini",
    released: "2025-11-13",
  },
  {
    kind: "model",
    id: "openrouter/moonshotai/kimi-k2-thinking",
    vendor: "moonshotai",
    name: "MoonshotAI: Kimi K2 Thinking",
    released: "2025-11-06",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5-pro",
    vendor: "openai",
    name: "OpenAI: GPT-5 Pro",
    released: "2025-10-06",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5-pro:batch",
    vendor: "openai",
    name: "OpenAI: GPT-5 Pro (batch)",
    released: "2025-10-06",
  },
  {
    kind: "model",
    id: "openrouter/z-ai/glm-4.6",
    vendor: "z-ai",
    name: "Z.ai: GLM 4.6",
    released: "2025-09-30",
  },
  {
    kind: "model",
    id: "openrouter/deepseek/deepseek-v3.2-exp",
    vendor: "deepseek",
    name: "DeepSeek: DeepSeek V3.2 Exp",
    released: "2025-09-29",
  },
  {
    kind: "model",
    id: "openrouter/deepseek/deepseek-v3.1-terminus",
    vendor: "deepseek",
    name: "DeepSeek: DeepSeek V3.1 Terminus",
    released: "2025-09-22",
  },
  {
    kind: "model",
    id: "openrouter/moonshotai/kimi-k2-0905",
    vendor: "moonshotai",
    name: "MoonshotAI: Kimi K2 0905",
    released: "2025-09-04",
  },
  {
    kind: "model",
    id: "openrouter/deepseek/deepseek-chat-v3.1",
    vendor: "deepseek",
    name: "DeepSeek: DeepSeek V3.1",
    released: "2025-08-21",
  },
  {
    kind: "model",
    id: "openrouter/z-ai/glm-4.5v",
    vendor: "z-ai",
    name: "Z.ai: GLM 4.5V",
    released: "2025-08-11",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5",
    vendor: "openai",
    name: "OpenAI: GPT-5",
    released: "2025-08-07",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5:batch",
    vendor: "openai",
    name: "OpenAI: GPT-5 (batch)",
    released: "2025-08-07",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5-mini",
    vendor: "openai",
    name: "OpenAI: GPT-5 Mini",
    released: "2025-08-07",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5-mini:batch",
    vendor: "openai",
    name: "OpenAI: GPT-5 Mini (batch)",
    released: "2025-08-07",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5-nano",
    vendor: "openai",
    name: "OpenAI: GPT-5 Nano",
    released: "2025-08-07",
  },
  {
    kind: "model",
    id: "openrouter/openai/gpt-5-nano:batch",
    vendor: "openai",
    name: "OpenAI: GPT-5 Nano (batch)",
    released: "2025-08-07",
  },
  {
    kind: "model",
    id: "openrouter/z-ai/glm-4.5",
    vendor: "z-ai",
    name: "Z.ai: GLM 4.5",
    released: "2025-07-25",
  },
  {
    kind: "model",
    id: "openrouter/z-ai/glm-4.5-air",
    vendor: "z-ai",
    name: "Z.ai: GLM 4.5 Air",
    released: "2025-07-25",
  },
  {
    kind: "model",
    id: "openrouter/google/gemini-2.5-flash-lite",
    vendor: "google",
    name: "Google: Gemini 2.5 Flash Lite",
    released: "2025-07-22",
  },
  {
    kind: "model",
    id: "openrouter/google/gemini-2.5-flash-lite:batch",
    vendor: "google",
    name: "Google: Gemini 2.5 Flash Lite (batch)",
    released: "2025-07-22",
  },
  {
    kind: "model",
    id: "openrouter/moonshotai/kimi-k2",
    vendor: "moonshotai",
    name: "MoonshotAI: Kimi K2 0711",
    released: "2025-07-11",
  },
  {
    kind: "model",
    id: "openrouter/google/gemini-2.5-flash",
    vendor: "google",
    name: "Google: Gemini 2.5 Flash",
    released: "2025-06-17",
  },
  {
    kind: "model",
    id: "openrouter/google/gemini-2.5-flash:batch",
    vendor: "google",
    name: "Google: Gemini 2.5 Flash (batch)",
    released: "2025-06-17",
  },
  {
    kind: "model",
    id: "openrouter/google/gemini-2.5-pro",
    vendor: "google",
    name: "Google: Gemini 2.5 Pro",
    released: "2025-06-17",
  },
  {
    kind: "model",
    id: "openrouter/google/gemini-2.5-pro:batch",
    vendor: "google",
    name: "Google: Gemini 2.5 Pro (batch)",
    released: "2025-06-17",
  },
  {
    kind: "model",
    id: "openrouter/google/gemini-2.5-pro-preview",
    vendor: "google",
    name: "Google: Gemini 2.5 Pro Preview 06-05",
    released: "2025-06-05",
  },
  {
    kind: "model",
    id: "openrouter/deepseek/deepseek-r1-0528",
    vendor: "deepseek",
    name: "DeepSeek: R1 0528",
    released: "2025-05-28",
  },
  {
    kind: "model",
    id: "openrouter/deepseek/deepseek-chat-v3-0324",
    vendor: "deepseek",
    name: "DeepSeek: DeepSeek V3 0324",
    released: "2025-03-24",
  },
  {
    kind: "model",
    id: "openrouter/deepseek/deepseek-r1",
    vendor: "deepseek",
    name: "DeepSeek: R1",
    released: "2025-01-20",
  },
  {
    kind: "model",
    id: "openrouter/deepseek/deepseek-chat",
    vendor: "deepseek",
    name: "DeepSeek: DeepSeek V3",
    released: "2024-12-26",
  },
  {
    kind: "preset",
    id: "openrouter/@preset/deepseek-v4-1-flash",
    name: "deepseek v4.1 flash, latency optimized",
    model: "openrouter/deepseek/deepseek-v4.1-flash",
  },
  {
    kind: "preset",
    id: "openrouter/@preset/glm5-3",
    name: "glm5.3, latency optimized",
    model: "openrouter/z-ai/glm-5.3",
  },
];
